# Generated by Django 2.2 on 2020-01-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='concert',
        ),
        migrations.AddField(
            model_name='concert',
            name='reviews',
            field=models.ManyToManyField(to='main_app.Review'),
        ),
    ]
